### PR TITLE
Add Appveyor configuration for Windows

### PR DESCRIPTION
**Pull request by antiagainst**
Set up testing on Windows

### CODE REVIEW

**Comment by mcharsley** [comment]
As per previous PR: have you checked that it works on Windows? I've been meaning to check on my home machine, now we've got publicly available source, but my evenings have been too busy so far.

I'd guess a 50:50 chance that it will fail with "/" vs "\" errors.

**Comment by antiagainst** [comment]
Yep, you are right. The Windows bot is already yelling at that.

**Comment by mcharsley** [comment]
And worse, not even consistent separators:

"./test_data/size\\512bytes"

**Comment by mcharsley** [comment]
#21 should unblock this

**Comment by mcharsley** [comment]
Windows fixes are now submitted. in #21 Do you want to retry this change now?

**Comment by antiagainst** [comment]
Yay! Works now!

**Pull request merged**
